### ISSUE TITLE
Extending suite of scheme

### ISSUE THREAD

**Issue by chaitanyabsprip** [yashguptaz/calvera-dark.nvim#12]
It would be awesome if you could provide with a colors-cheme for terminals like kitty/alacritty and if I'm being ambitious, maybe for shells like fish/zsh. I am currently using tokyonight and they have provided the whole suite of color-schemes, probably generated it using something, I am not sure. I would really appreciate if you could do this.

**Comment by AlphaTechnolog** [comment]
I create a simple alacritty calvera dark theme:

```yaml
calvera_dark: &calvera_dark
  primary:
    background: "#0c0c1f"
    foreground: "#B0BEC5"
  cursor:
    text: CellBackground
    cursor: "#AAB4EC"
  normal:
    black: "#000000"
    red: "#E97A7A"
    green: "#ADCEA1"
    yellow: "#D6B295"
    blue: "#82AAFF"
    magenta: "#C792EA"
    cyan: "#7878E7"
    white: "#FFFFFF"
  bright:
    black: "#717CB4"
    red: "#FF5370"
    green: "#ADCEA1"
    yellow: "#D6B295"
    blue: "#82AAFF"
    magenta: "#FF9CAC"
    cyan: "#7878E7"
    white: "#B0BEC5"

```
